/* JJK Energy · veri personaggi WebGL 3D e tecniche animate */
(function(){
'use strict';
const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';
const reduced=matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;
const mobile=matchMedia?.('(max-width:760px)')?.matches;
const DATA={
 gojo:{a:0x65d6ff,b:0xa954ff,skin:0xf0c7ad,hair:0xf5f7ff,top:0x111827,bottom:0x090f1c,moves:[['Bagliore Blu','blue'],['Bagliore Rosso','red'],['Bagliore Viola','purple'],['Infinito','domain']]},
 sukuna:{a:0xff405b,b:0xff9b3d,skin:0xe8b49c,hair:0xee8a99,top:0xe7d9cf,bottom:0x3a1017,moves:[['Taglio','slash'],['World Slash','world'],['Freccia Infuocata','fire'],['Reliquiario Maledetto','domain']]},
 itadori:{a:0xff6688,b:0xd91645,skin:0xe8b49c,hair:0xe88791,top:0x151923,bottom:0xd4244b,moves:[['Pugno Divergente','impact'],['Black Flash','black'],['Freccia Infuocata','fire'],['Santuario Benevolo','domain']]},
 megumi:{a:0x38d9ff,b:0x143e75,skin:0xe5b398,hair:0x10141c,top:0x101827,bottom:0x0b111d,moves:[['Cani Divini','shadow'],['Nue','shadow'],['Mahoraga','summon'],['Giardino delle Ombre','domain']]},
 geto:{a:0x4be497,b:0x7c54ff,skin:0xe2b093,hair:0x111016,top:0x17101f,bottom:0x08070b,moves:[['Sciame di Maledizioni','orbs'],['Drago Arcobaleno','summon'],['Uzumaki','purple'],['Tamamo-no-Mae','domain']]},
 mahito:{a:0xb762ff,b:0xff5ba8,skin:0xd7b39f,hair:0x9bb5c8,top:0x282f3a,bottom:0x141820,moves:[['Distorsione Corporea','distort'],['Trasfigurazione Inerte','impact'],['Trasfigurazione Perfetta','black'],['Autoreincarnazione','domain']]},
 jogo:{a:0xff7a32,b:0xffd35a,skin:0xc7bbb0,hair:0x6e635b,top:0x3b2117,bottom:0x21100b,moves:[['Insetti Ardenti','fire'],['Vulcani','fire'],['Meteora Infuocata','meteor'],['Bara della Montagna di Ferro','domain']]},
 toji:{a:0x9e68ff,b:0xd5e0ff,skin:0xc99478,hair:0x121319,top:0x16191d,bottom:0x222733,moves:[['Velocità Sovrumana','speed'],['Lancia Celeste Invertita','slash'],['Potenza Sovrumana','impact'],['Frenesia Omicida','world']]},
 yuta:{a:0x6597ff,b:0xc5d9ff,skin:0xe1b196,hair:0x11141d,top:0xe5e7eb,bottom:0x121722,moves:[['Katana Maledetta','slash'],['Manifestazione di Rika','summon'],['Copia','orbs'],['Mondo di Katane','domain']]}
};
let THREE,loading,raf,last=performance.now();
const stages=new Map(),ids=Object.keys(DATA),q=(s,r=document)=>r?.querySelector?.(s)||null;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)};
function loadThree(){return THREE?Promise.resolve(THREE):loading||(loading=import(THREE_URL).then(m=>THREE=m));}
function detect(el){const t=((el?.dataset?.r3dCharacter||el?.dataset?.v34Character||el?.dataset?.v34Roster||el?.getAttribute?.('onclick')||'')+' '+(q('img',el)?.src||'')).toLowerCase();return ids.find(id=>t.includes(id))||null;}
function mountFor(host){if(host.id==='characterInfoStage')return q('.character-info-image-wrap',host)||q('.character-info-portrait',host);if(host.id==='roomDraftStage')return q('.room-draft-portrait',host);return host;}
function mat(c,glow=0){return new THREE.MeshStandardMaterial({color:c,roughness:.55,metalness:.08,emissive:glow?c:0,emissiveIntensity:glow});}
function gmat(c,o=.9){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide});}
function add(parent,geo,ma,p=[0,0,0],r=[0,0,0],s=[1,1,1]){const m=new THREE.Mesh(geo,ma);m.position.set(...p);m.rotation.set(...r);m.scale.set(...s);m.castShadow=true;parent.add(m);return m;}
function limb(root,x,y,cloth,skin,leg=false){const a=new THREE.Group();a.position.set(x,y,0);root.add(a);add(a,new THREE.CapsuleGeometry(leg?.16:.13,leg?.9:.68,4,7),cloth,[0,leg?-.48:-.38,0]);const b=new THREE.Group();b.position.y=leg?-.98:-.76;a.add(b);add(b,new THREE.CapsuleGeometry(leg?.14:.11,leg?.78:.58,4,7),leg?cloth:skin,[0,leg?-.42:-.33,0]);const hand=new THREE.Group();hand.position.y=leg?-.88:-.68;b.add(hand);if(leg)add(hand,new THREE.BoxGeometry(.3,.17,.55),cloth,[0,0,.13]);else add(hand,new THREE.SphereGeometry(.15,10,8),skin);return{a,b,hand};}
function hair(head,c,id){const hm=mat(c);if(id==='jogo'){add(head,new THREE.ConeGeometry(.25,.72,10),hm,[0,.58,0]);add(head,new THREE.ConeGeometry(.13,.34,8),gmat(0xff7a32),[0,1.02,0]);return;}add(head,new THREE.SphereGeometry(.48,16,12),hm,[0,.12,0],[0,0,0],[1,.8,1]);const n=id==='megumi'?12:8;for(let i=0;i<n;i++){const a=i/n*Math.PI*2;add(head,new THREE.ConeGeometry(.1,.42+(i%3)*.07,6),hm,[Math.cos(a)*.38,.42+(i%2)*.08,Math.sin(a)*.38],[Math.sin(a)*.45,0,-Math.cos(a)*.45]);}}
function weapon(hand,id){if(id!=='yuta'&&id!=='toji')return;const metal=mat(0xdbe8ff),dark=mat(0x171922);const h=new THREE.Group();hand.add(h);add(h,new THREE.CylinderGeometry(.035,.035,id==='toji'?2.1:1.35,7),id==='toji'?dark:metal,[0,id==='toji'?-1.02:-.7,0]);if(id==='toji')add(h,new THREE.ConeGeometry(.12,.42,7),metal,[0,-2.28,0],[Math.PI,0,0]);else{add(h,new THREE.CylinderGeometry(.065,.065,.36,7),dark,[0,.18,0]);add(h,new THREE.BoxGeometry(.32,.06,.08),metal);}}
function fighter(id){const c=DATA[id],root=new THREE.Group(),skin=mat(c.skin),top=mat(c.top),bottom=mat(c.bottom),body=new THREE.Group();root.add(body);add(body,new THREE.CapsuleGeometry(id==='toji'?.52:.45,.86,5,10),top,[0,2.3,0],[0,0,0],[1,1,.72]);add(body,new THREE.CapsuleGeometry(.33,.34,4,8),bottom,[0,1.45,0]);add(body,new THREE.CylinderGeometry(.14,.16,.22,9),skin,[0,3.02,0]);const head=new THREE.Group();head.position.set(0,3.43,0);body.add(head);add(head,new THREE.SphereGeometry(id==='jogo'?.41:.45,18,14),skin,[0,0,0],[0,0,0],[1,1.08,.93]);hair(head,c.hair,id);if(id==='gojo')add(head,new THREE.BoxGeometry(.8,.2,.15),mat(0x080a10),[0,.02,.39]);if(id==='sukuna'){const mark=mat(0x1a1015);add(head,new THREE.BoxGeometry(.28,.025,.025),mark,[-.2,-.04,.45],[0,0,.2]);add(head,new THREE.BoxGeometry(.28,.025,.025),mark,[.2,-.04,.45],[0,0,-.2]);}const la=limb(body,-.62,2.74,top,skin),ra=limb(body,.62,2.74,top,skin),ll=limb(body,-.27,1.38,bottom,skin,true),rl=limb(body,.27,1.38,bottom,skin,true);weapon(ra.hand,id);root.userData={id,body,head,la,ra,ll,rl};root.scale.setScalar(mobile?.82:.92);return root;}
function reset(f,t){const j=f.userData;f.position.set(0,Math.sin(t*1.7)*.025,0);f.rotation.y=Math.sin(t*.45)*.035;j.body.rotation.set(0,0,Math.sin(t*.8)*.012);j.head.rotation.set(0,Math.sin(t*.55)*.04,0);j.la.a.rotation.set(.05,0,.08);j.ra.a.rotation.set(.05,0,-.08);j.la.b.rotation.set(-.08,0,0);j.ra.b.rotation.set(-.08,0,0);}
function pose(f,type,p,t){reset(f,t);const j=f.userData,r=ease(clamp(p/.3)),hit=ease(clamp((p-.48)/.3));if(/slash|world|speed/.test(type)){j.ra.a.rotation.x=-1.2*r;j.ra.a.rotation.z=-1.05*r+2.1*hit;j.body.rotation.y=-.55*r+.95*hit;}else if(/impact|black/.test(type)){j.ra.a.rotation.x=-1.55*r;j.body.rotation.y=-.45*r+.75*hit;f.position.z=.65*hit;}else if(/blue|red|purple|fire|orbs|meteor/.test(type)){j.la.a.rotation.x=j.ra.a.rotation.x=-1.2*r;j.la.a.rotation.z=.35*r;j.ra.a.rotation.z=-.35*r;}else{j.la.a.rotation.x=j.ra.a.rotation.x=-.62*r;j.la.a.rotation.z=-1.05*r;j.ra.a.rotation.z=1.05*r;}}
function fxMesh(stage,geo,ma,p=[0,0,0],r=[0,0,0]){return add(stage.fx,geo,ma,p,r);}
function spawn(stage,type){const c=stage.cfg,e={type,start:stage.now,d:2,objects:[]};if(type==='blue'||type==='red'||type==='purple'){const col=type==='blue'?0x2da8ff:type==='red'?0xff355e:0x8c3cff;e.objects.push(fxMesh(stage,new THREE.SphereGeometry(type==='purple'?.42:.3,20,14),gmat(col),[.55,2.55,.65]));e.objects.push(fxMesh(stage,new THREE.PointLight(col,5,9),gmat(col),[.55,2.55,.65]));}
 else if(type==='slash'||type==='world'||type==='speed'){for(let i=0;i<(type==='world'?4:2);i++)e.objects.push(fxMesh(stage,new THREE.PlaneGeometry(type==='world'?7:5,.08),gmat(c.a),[0,2.35,.75+i*.03],[0,0,(i%2?-1:1)*.58]));}
 else if(type==='impact'||type==='black'){const col=type==='black'?0xff174d:c.a;for(let i=0;i<4;i++)e.objects.push(fxMesh(stage,new THREE.TorusGeometry(.25+i*.09,.035,7,28),gmat(i%2?col:0xffffff),[.55,2.45,.72]));}
 else if(type==='fire'||type==='meteor'){e.objects.push(fxMesh(stage,new THREE.IcosahedronGeometry(type==='meteor'?.65:.3,2),gmat(0xff6a22),type==='meteor'?[-1.4,5.8,-1.2]:[.5,2.55,.7]));}
 else if(type==='shadow'||type==='summon'){e.objects.push(fxMesh(stage,new THREE.CapsuleGeometry(type==='summon'?.55:.32,type==='summon'?1.6:.85,5,8),mat(0x050812,.28),[type==='summon'?-.2:.8,type==='summon'?1.45:.85,-.3]));e.objects.push(fxMesh(stage,new THREE.CircleGeometry(type==='summon'?1.45:1,30),gmat(c.a,.4),[0,.02,0],[-Math.PI/2,0,0]));}
 else if(type==='distort'){for(let i=0;i<3;i++)e.objects.push(fxMesh(stage,new THREE.TorusKnotGeometry(.28+i*.08,.035,54,8,2,3),gmat(i%2?c.a:c.b),[.2,2.4,.45]));}
 else if(type==='orbs'){for(let i=0;i<12;i++){const o=fxMesh(stage,new THREE.SphereGeometry(.06+(i%3)*.015,9,7),gmat(i%2?c.a:c.b),[0,2.3,.2]);o.userData.i=i;e.objects.push(o);}}
 else{e.d=2.3;e.objects.push(fxMesh(stage,new THREE.SphereGeometry(1.15,24,16),gmat(c.a,.28),[0,2.05,0]));for(let i=0;i<4;i++)e.objects.push(fxMesh(stage,new THREE.TorusGeometry(1.1+i*.22,.035,8,34),gmat(i%2?c.a:c.b),[0,2.05,0],[i%2?Math.PI/2:0,i*.4,0]));}
 stage.effects.push(e);}
function updateFx(stage,e,p){const out=1-ease(clamp((p-.72)/.28));e.objects.forEach((o,i)=>{if(o.material?.opacity!==undefined)o.material.opacity*=out;if(/blue|red|purple/.test(e.type)){const fly=ease(clamp((p-.48)/.52));o.position.z=.65+fly*5;o.scale.setScalar(.05+ease(clamp(p/.42))*(e.type==='purple'?1.45:1));}else if(/slash|world|speed/.test(e.type)){o.scale.x=.02+ease(clamp(p/.3))*(e.type==='world'?1.5:1);o.position.z=.75+ease(p)*6;}else if(/impact|black/.test(e.type)){o.scale.setScalar(.05+ease(clamp(p/.28))*1.3+ease(clamp((p-.22)/.78))*2.8);o.position.z=.72+ease(p)*3.5;}else if(/fire/.test(e.type)){o.position.z=.7+ease(p)*5.5;o.scale.setScalar(.08+ease(clamp(p/.4))*1.4);}else if(e.type==='meteor'){o.position.set(-1.4+ease(p)*1.5,5.8-ease(p)*3.1,-1.2+ease(p)*5.4);o.scale.setScalar(.25+ease(p)*1.5);o.rotation.set(p*8,p*5,p*3);}else if(e.type==='orbs'){const a=i/12*Math.PI*2+p*9,r=.7*(1-ease(clamp(p/.55))*.72);o.position.set(Math.cos(a)*r,2.3+Math.sin(a*1.3)*r*.7,.2+Math.sin(a)*r*.4+ease(clamp((p-.58)/.42))*4.7);}else{o.scale.setScalar(.08+ease(clamp(p/.5))*2.3);o.rotation.y=p*1.8;}});}
class Stage{constructor(host,id){this.host=host;this.mount=mountFor(host);this.cfg=DATA[id];this.id=id;this.now=0;this.next=performance.now()+900+Math.random()*1300;this.effects=[];this.fx=new THREE.Group();this.canvas=document.createElement('canvas');this.canvas.className='r3d-webgl-canvas';this.label=document.createElement('div');this.label.className='r3d-webgl-technique';this.label.innerHTML='<b></b><small>Tecnica casuale 3D</small>';this.badge=document.createElement('div');this.badge.className='r3d-webgl-badge';this.badge.textContent='3D LIVE';this.mount.classList.add('r3d-webgl-mount');this.mount.append(this.canvas,this.label,this.badge);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(31,1,.1,60);this.camera.position.set(0,2.35,8.8);this.camera.lookAt(0,2.1,0);this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,alpha:true,antialias:!mobile,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.25:1.8));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.scene.add(new THREE.HemisphereLight(0xb9d7ff,0x160f1f,2.7));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(3,7,6);this.scene.add(key);const floor=add(this.scene,new THREE.CircleGeometry(3.2,42),mat(0x09060f),[0,-.03,0],[-Math.PI/2,0,0]);floor.material.transparent=true;floor.material.opacity=.78;this.scene.add(this.fx);this.set(id);this.mount.addEventListener('click',()=>this.play(true));requestAnimationFrame(()=>this.mount.classList.add('r3d-webgl-ready'));}
 set(id){if(!DATA[id]||this.id===id&&this.f)return;this.id=id;this.cfg=DATA[id];this.host.dataset.r3dCharacter=id;if(this.f)this.f.removeFromParent();this.f=fighter(id);this.scene.add(this.f);this.effects.forEach(e=>e.objects.forEach(o=>o.removeFromParent()));this.effects=[];}
 resize(){const r=this.mount.getBoundingClientRect(),w=Math.max(2,r.width|0),h=Math.max(2,r.height|0);if(w===this.w&&h===this.h)return;this.w=w;this.h=h;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 play(user=false){if(this.attack)return;let m=this.cfg.moves[Math.floor(Math.random()*this.cfg.moves.length)];if(this.last===m[0])m=this.cfg.moves[(this.cfg.moves.indexOf(m)+1)%this.cfg.moves.length];this.last=m[0];this.attack={type:m[1],start:this.now,d:/domain|summon|meteor/.test(m[1])?2.3:1.8};this.label.querySelector('b').textContent=m[0];this.label.classList.remove('show');void this.label.offsetWidth;this.label.classList.add('show');spawn(this,m[1]);this.next=performance.now()+(user?5200:6500)+Math.random()*6500;window.JJKSfx?.play?.(/slash|world|speed/.test(m[1])?'slash':/fire|meteor/.test(m[1])?'fire':/impact|black/.test(m[1])?'impact':/shadow|summon/.test(m[1])?'shadow':/domain/.test(m[1])?'domain':'energy');}
 update(now,dt){this.now=now/1000;this.resize();if(this.attack){const p=(this.now-this.attack.start)/this.attack.d;if(p>=1){this.attack=null;this.label.classList.remove('show');reset(this.f,this.now);}else pose(this.f,this.attack.type,p,this.now);}else reset(this.f,this.now);if(!this.attack&&performance.now()>=this.next)this.play();for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i],p=(this.now-e.start)/e.d;if(p>=1){e.objects.forEach(o=>o.removeFromParent());this.effects.splice(i,1);}else updateFx(this,e,p);}this.renderer.render(this.scene,this.camera);}}
function ensure(host,id){if(!host||!DATA[id])return;let s=stages.get(host);if(s)s.set(id);else{stages.set(host,s=new Stage(host,id));}return s;}
function refresh(){const l=document.getElementById('v34HomeFighter');if(l)ensure(l,detect(l)||'gojo');const r=q('#v34HomeCinema .v34-home-fighter.right');if(r)ensure(r,'sukuna');const info=document.getElementById('characterInfoStage');if(info)ensure(info,detect(info)||(()=>{try{return uiInfoCharacterId}catch(_){return'gojo'}})());const draft=document.getElementById('roomDraftStage');if(draft)ensure(draft,detect(draft)||(()=>{try{return roomDraftCharacterId||'gojo'}catch(_){return'gojo'}})());}
function tick(now){const dt=Math.min(.05,(now-last)/1000||.016);last=now;stages.forEach((s,h)=>h.isConnected?s.update(now,dt):stages.delete(h));raf=requestAnimationFrame(tick);}
async function install(){if(reduced)return;try{await loadThree();document.documentElement.classList.add('r3d-webgl-enabled');refresh();new MutationObserver(()=>requestAnimationFrame(refresh)).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['src','data-v34-character']});raf=requestAnimationFrame(tick);}catch(e){console.error('[JJK 3D]',e);document.documentElement.classList.add('r3d-webgl-failed');}}
window.JJKRoster3D={refresh,playCharacter(id){const s=stages.get(document.getElementById('characterInfoStage'))||stages.get(document.getElementById('v34HomeFighter'));if(s){s.set(id);s.play(true);}},data:DATA,engine:'Three.js WebGL articulated fighters'};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();