/* JJK Energy V36 - Live Archive, Spectator, Admin & Rules Update */
(function(){
'use strict';

const VERSION='36.0.0';
const CLIENT_ID_KEY='jjk_v36_presence_client';
const TOJI_ACTIVE_KEY='jjk_toji_monster_active_v36';
const AUDIO_BOOST_KEY='jjk_v36_audio_boosted';
const gradeRank={G4:0,G3:1,G2:2,G1:3,SS:4,SG:5};
const state={activeStatsView:'overview',history:[],live:[],online:[],profile:null,progression:null,admin:false,adminAccounts:[],spectatorRoomId:null,spectatorTimer:null,presenceTimer:null,onlineTimer:null,roomSheetTimer:null,initialized:false};
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function num(value){const n=Number(value);return Number.isFinite(n)?n:0;}
function clamp(value,min,max){return Math.max(min,Math.min(max,num(value)));}
function int(value){return Math.round(num(value)).toLocaleString('it-IT');}
function fmtDate(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d);}
function fmtDuration(seconds){const total=Math.max(0,Math.floor(num(seconds))),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;if(h)return h+'h '+String(m).padStart(2,'0')+'m';if(m)return m+'m '+String(s).padStart(2,'0')+'s';return s+'s';}
function getRoom(){try{return roomSession||window.roomSession||null;}catch(_){return window.roomSession||null;}}
function getCharacters(){try{return characters||window.characters||{};}catch(_){return window.characters||{};}}
function getCurrentId(){try{return currentId||window.currentId||null;}catch(_){return window.currentId||null;}}
function getGrade(){try{return gradeId||'G4';}catch(_){return 'G4';}}
function getLocalPlayer(){try{return typeof getLocalRoomPlayer==='function'?getLocalRoomPlayer():null;}catch(_){return null;}}
function rankOf(id){return gradeRank[id]??0;}
function characterName(id){const c=getCharacters()[id];return c?.name||id||'—';}
function characterImage(id){return getCharacters()[id]?.image||'';}
function activeScreen(){return document.querySelector('.screen.active')?.id||'home';}
function setGlobal(name,fn){window[name]=fn;try{eval(name+' = fn');}catch(_){}}
function getGlobal(name){try{return window[name]||eval(name);}catch(_){return window[name];}}
function notify(title,text,color='#62c7ff'){try{if(typeof showPlayerNotification==='function')return showPlayerNotification(title,text,color);}catch(_){}try{if(typeof showModal==='function')return showModal(title,'',text);}catch(_){}console.info('[JJK V36]',title,text);}
async function cloudReady(){if(window.jjkEnsureCloudReady)await window.jjkEnsureCloudReady();if(!window.jjkSupabase&&window.JJKAccount?.getClient)window.jjkSupabase=window.JJKAccount.getClient();if(!window.jjkSupabase)throw new Error('Connessione Supabase non disponibile.');return window.jjkSupabase;}
async function rpc(name,args={}){if(window.jjkCloudRpc)return window.jjkCloudRpc(name,args);const client=await cloudReady();const {data,error}=await client.rpc(name,args);if(error)throw error;if(typeof data==='string'){try{return JSON.parse(data);}catch(_){return data;}}return data;}
function migrationError(error){const text=String(error?.message||error||'');return /jjk_.*v36|function .* does not exist|schema cache/i.test(text);}
function requirementBox(){return '<div class="v36-requirement"><b>Attivazione cloud V36 richiesta</b><span>Esegui una sola volta in Supabase il file <code>JJK_Supabase_Passo_10_V36_Storico_Live_Admin.sql</code>. Il resto del sito continua a funzionare normalmente.</span></div>';}

function patchCharacterRules(){const chars=getCharacters(),jogo=chars.jogo,toji=chars.toji;if(jogo){jogo.maxLife=8;jogo.baseBody=5;jogo.resourceLimit=8;jogo.lifeEnergyLinked=true;const find=key=>jogo.techniques?.find(t=>t.key===key);Object.assign(find('meteora')||{},{effect:'Tecnica di combattimento: +4 Corpo. Nessun costo; Jogo usa Vita ed Energia come un unico valore, massimo 8.'});Object.assign(find('mobilita')||{},{effect:'Passiva: durante il movimento puoi avanzare fino a 6 caselle. Non consente movimenti aggiuntivi oltre questo limite.'});Object.assign(find('inversione')||{},{heal:1,effect:'Recupera esattamente 1 Vita/Energia, senza superare 8. Per usare questa tecnica devi rinunciare completamente al movimento del turno.'});Object.assign(find('meteora2')||{},{effect:'Tecnica di combattimento: +6 Corpo. Nessun costo; Vita ed Energia restano collegate.'});Object.assign(find('magmatico')||{},{effect:'Passiva difensiva: quando vieni attaccato tira 1d6 una sola volta. Con 1-3 nessun effetto; con 4-6 l’attaccante riceve −1 Combattimento per quello scontro.'});Object.assign(find('calore')||{},{heatMax:8,effect:'Passiva SG: ottieni +1 Calore soltanto dopo una vittoria PvP. Ogni Calore vale +1 Corpo permanente finché resta accumulato, massimo 8.'});}if(toji){const monster=toji.techniques?.find(t=>t.key==='mostro');if(monster){monster.passive=true;monster.effect='Passiva automatica dal grado SS in poi: +2 Corpo base e +2 Vita massima. L’effetto resta attivo anche al grado SG e si disattiva sotto SS.';}}}
function tojiMonsterEligible(id=getCurrentId(),grade=getGrade()){return id==='toji'&&rankOf(grade)>=rankOf('SS');}
function showTojiUnlockFx(){let fx=document.getElementById('v36TojiUnlock');if(!fx){fx=document.createElement('div');fx.id='v36TojiUnlock';fx.className='v36-toji-unlock';fx.innerHTML='<div class="v36-toji-slash"></div><section><small>PASSIVA SBLOCCATA</small><h2>Mostro Senza Energia Maledetta</h2><p>+2 Corpo base · +2 Vita massima</p></section>';document.body.appendChild(fx);}fx.classList.remove('show');void fx.offsetWidth;fx.classList.add('show');try{window.JJKSfx?.play('slash');window.JJKSfx?.play('impact');}catch(_){}setTimeout(()=>fx.classList.remove('show'),2800);}
function syncLocalTojiMonster(showFx=false){const chars=getCharacters(),toji=chars.toji;if(!toji)return false;const active=tojiMonsterEligible(),was=localStorage.getItem(TOJI_ACTIVE_KEY)==='1';toji.maxLife=active?10:8;if(getCurrentId()==='toji'){try{if(active&&!was){life=Math.min(10,Math.max(0,num(life))+2);localStorage.setItem(TOJI_ACTIVE_KEY,'1');if(showFx)showTojiUnlockFx();try{addLog('Mostro Senza Energia Maledetta','Passiva attiva: +2 Corpo base e +2 Vita massima.');}catch(_){}}else if(!active&&was){life=Math.min(8,num(life));localStorage.setItem(TOJI_ACTIVE_KEY,'0');try{addLog('Passiva disattivata','Mostro Senza Energia Maledetta non è più attivo sotto il grado SS.');}catch(_){}}const maxEl=document.getElementById('lifeMaxValue');if(maxEl)maxEl.textContent=active?10:8;}catch(_){}}return active;}
function normalizeTojiRoomState(player){if(!player?.state||player.characterId!=='toji')return player?.state;const s=player.state,active=rankOf(s.gradeId||'G4')>=rankOf('SS');if(active&&!s.tojiMonsterActive)s.life=Math.min(10,Math.max(0,num(s.life))+2);if(!active&&s.tojiMonsterActive)s.life=Math.min(8,num(s.life));s.tojiMonsterActive=active;s.maxLife=active?10:8;s.updatedAt=Date.now();return s;}
function installTojiRules(){const originalBody=getGlobal('effectiveBaseBody');if(typeof originalBody==='function'&&!originalBody.__v36){const wrapped=function(){const base=num(originalBody.apply(this,arguments));return base+(tojiMonsterEligible()?2:0);};wrapped.__v36=true;setGlobal('effectiveBaseBody',wrapped);}const originalSync=getGlobal('syncGrade');if(typeof originalSync==='function'&&!originalSync.__v36){const wrapped=function(showPromotion){const before=getGrade(),out=originalSync.apply(this,arguments),after=getGrade();syncLocalTojiMonster(showPromotion&&rankOf(after)>=rankOf('SS')&&rankOf(before)<rankOf('SS'));try{renderAll();}catch(_){}return out;};wrapped.__v36=true;setGlobal('syncGrade',wrapped);}const originalOpen=getGlobal('openCharacter');if(typeof originalOpen==='function'&&!originalOpen.__v36){const wrapped=function(){const out=originalOpen.apply(this,arguments);syncLocalTojiMonster(false);return out;};wrapped.__v36=true;setGlobal('openCharacter',wrapped);}const originalBuild=getGlobal('buildLocalPlayerState');if(typeof originalBuild==='function'&&!originalBuild.__v36){const wrapped=function(){syncLocalTojiMonster(false);const s=originalBuild.apply(this,arguments);if(s?.characterId==='toji'){const active=rankOf(s.gradeId||'G4')>=rankOf('SS');s.tojiMonsterActive=active;s.maxLife=active?10:8;}if(s?.characterId==='jogo'){s.maxLife=8;s.life=clamp(s.life,0,8);s.jogoLife=s.life;s.energy=s.life;s.jogoHeat=clamp(s.jogoHeat,0,8);}return s;};wrapped.__v36=true;setGlobal('buildLocalPlayerState',wrapped);}const originalInitial=getGlobal('createInitialRoomPlayerState');if(typeof originalInitial==='function'&&!originalInitial.__v36){const wrapped=function(characterId){const s=originalInitial.apply(this,arguments)||{};if(characterId==='toji'){s.tojiMonsterActive=false;s.maxLife=8;}if(characterId==='jogo'){s.life=8;s.maxLife=8;s.energy=8;s.jogoLife=8;s.jogoHeat=0;}return s;};wrapped.__v36=true;setGlobal('createInitialRoomPlayerState',wrapped);}const originalAdjust=getGlobal('adjustRoomStateObject');if(typeof originalAdjust==='function'&&!originalAdjust.__v36){const wrapped=function(player,field,delta){const out=originalAdjust.apply(this,arguments);if(player?.characterId==='toji')normalizeTojiRoomState(player);if(player?.characterId==='jogo'&&player.state){const s=player.state;s.life=clamp(s.life,0,8);s.energy=s.life;s.jogoLife=s.life;s.maxLife=8;s.jogoHeat=clamp(s.jogoHeat,0,8);}return out;};wrapped.__v36=true;setGlobal('adjustRoomStateObject',wrapped);}}
function permanentBodyLocked(){const room=getRoom(),me=getLocalPlayer();return !!(room?.phase==='playing'&&!room.isHost&&me&&!me.isHost);}
function installPermanentBodyGuard(){const original=getGlobal('changeCombatBonus');if(typeof original==='function'&&!original.__v36){const wrapped=function(){if(permanentBodyLocked()){notify('Corpo permanente bloccato','Durante una partita online il Bonus Corpo può essere modificato soltanto dal Game Master.','#ff9b55');return;}return original.apply(this,arguments);};wrapped.__v36=true;setGlobal('changeCombatBonus',wrapped);}const update=()=>{document.querySelectorAll('[onclick*="changeCombatBonus"]').forEach(button=>{const locked=permanentBodyLocked();button.disabled=locked;button.classList.toggle('v36-gm-only',locked);button.title=locked?'Modificabile soltanto dal Game Master durante la partita':'';});const box=document.querySelector('.combat-bonus-panel,.combat-panel');if(box){let note=box.querySelector('.v36-body-lock-note');if(permanentBodyLocked()&&!note){note=document.createElement('div');note.className='v36-body-lock-note';note.textContent='🔒 Corpo permanente gestito dal Game Master';box.appendChild(note);}else if(!permanentBodyLocked())note?.remove();}};setInterval(update,1200);update();}

function specialRows(player){const s=player?.state||{},id=player?.characterId,rows=[];if(id==='geto')rows.push(['Segnalini',s.tokens||0]);if(id==='jogo')rows.push(['Calore',(s.jogoHeat||0)+' / 8']);if(id==='toji')rows.push(['Energia raccolta',(s.tojiCollectedEnergy||0)+' / 20']);if(id==='itadori')rows.push(['Dita',s.itadoriFingers||0]);if(id==='megumi')rows.push(['Shikigami',s.megumiCompanionOn?'Al seguito':'Separato']);if(id==='yuta'&&s.yutaCopiedTechnique)rows.push(['Copia',s.yutaCopiedTechnique.techName||s.yutaCopiedTechnique.name||'Tecnica']);if(s.pvpPoints!==undefined)rows.push(['Punti PVP',(s.pvpPoints||0)+' / 2']);return rows;}
function unlockedTechniques(player){const ch=getCharacters()[player.characterId],grade=player.state?.gradeId||'G4';if(!ch)return [];return (ch.techniques||[]).filter(t=>rankOf(t.grade)<=rankOf(grade)&&!(player.characterId==='itadori'&&t.fingerOnly&&num(player.state?.itadoriMaxFingers)<num(t.fingerReq)));}
function readOnlyPlayerCard(player,compact=false){const s=player.state||{},ch=getCharacters()[player.characterId],max=s.maxLife??ch?.maxLife??'—',resource=player.characterId==='toji'?'Vigore':player.characterId==='jogo'?'Vita / Energia':'Energia';return '<article class="v36-sheet-card '+(player.locked?'locked':'active')+'"><header><img src="'+esc(ch?.image||'')+'" alt=""><div><small>'+(player.connected===false?'Offline / riconnessione':player.locked?'In attesa':'Turno attivo')+'</small><h3>'+esc(player.name||'Giocatore')+'</h3><p>'+esc(ch?.name||'Nessun personaggio')+'</p></div><span>'+esc(s.gradeId||'G4')+'</span></header><div class="v36-sheet-stats"><div><small>Vita</small><b>'+esc(s.life??'—')+' / '+esc(max)+'</b></div><div><small>'+resource+'</small><b>'+esc(s.energy??s.life??'—')+'</b></div><div><small>EXP</small><b>'+esc(s.exp??0)+'</b></div><div><small>Corpo</small><b>'+esc((ch?.baseBody||0)+(player.characterId==='toji'&&rankOf(s.gradeId)>=rankOf('SS')?2:0)+(s.combatBonus||0))+'</b></div></div>'+(specialRows(player).length?'<div class="v36-special-row">'+specialRows(player).map(([k,v])=>'<span><small>'+esc(k)+'</small><b>'+esc(v)+'</b></span>').join('')+'</div>':'')+(compact?'':'<details><summary>Tecniche sbloccate · '+unlockedTechniques(player).length+'</summary><div class="v36-tech-list">'+unlockedTechniques(player).map(t=>'<div><b>'+esc(t.grade)+'</b><span>'+esc(t.name)+'</span><small>'+(t.bonus!==null&&t.bonus!==undefined?'+'+t.bonus+' Corpo':esc(t.effect||t.extra||'Effetto speciale'))+'</small></div>').join('')+'</div></details>')+'</article>';}
function ensureRoomSheetsUi(){if(!document.getElementById('v36OtherSheetsBtn')){const btn=document.createElement('button');btn.id='v36OtherSheetsBtn';btn.className='v36-other-sheets-btn';btn.type='button';btn.innerHTML='<span>戦</span><b>Consulta avversari</b><small>Schede in sola lettura</small>';btn.addEventListener('click',openOtherSheets);document.body.appendChild(btn);}if(!document.getElementById('v36OtherSheetsModal')){const modal=document.createElement('div');modal.id='v36OtherSheetsModal';modal.className='v36-modal';modal.innerHTML='<section class="v36-modal-shell v36-sheets-shell"><header><div><small>Strategia in attesa</small><h2>Schede degli altri giocatori</h2><p>Puoi studiare risorse, grado e tecniche, senza modificare nulla.</p></div><button data-v36-close="sheets">✕</button></header><div id="v36OtherSheetsContent" class="v36-sheet-grid"></div></section>';document.body.appendChild(modal);}}
function updateOtherSheetsButton(){const btn=document.getElementById('v36OtherSheetsBtn'),room=getRoom(),me=getLocalPlayer();if(!btn)return;const visible=!!(room?.phase==='playing'&&!room.isHost&&me?.locked&&room.players?.some(p=>!p.isHost&&p.playerToken!==me.playerToken));btn.classList.toggle('show',visible);if(!visible)closeOtherSheets();}
function renderOtherSheets(){const root=document.getElementById('v36OtherSheetsContent'),room=getRoom(),me=getLocalPlayer();if(!root||!room)return;const players=(room.players||[]).filter(p=>!p.isHost&&p.playerToken!==me?.playerToken&&p.characterId);root.innerHTML=players.length?players.map(p=>readOnlyPlayerCard(p)).join(''):'<div class="v36-empty">Nessun altro giocatore disponibile.</div>';}
function openOtherSheets(){const modal=document.getElementById('v36OtherSheetsModal');if(!modal)return;renderOtherSheets();modal.classList.add('show');clearInterval(state.roomSheetTimer);state.roomSheetTimer=setInterval(renderOtherSheets,2500);}
function closeOtherSheets(){document.getElementById('v36OtherSheetsModal')?.classList.remove('show');clearInterval(state.roomSheetTimer);state.roomSheetTimer=null;}
function injectJogoQuickControls(){const room=getRoom();if(!room?.isHost||room.phase!=='playing')return;document.querySelectorAll('.gm-player-card[data-player-token]').forEach(card=>{const player=(room.players||[]).find(p=>String(p.playerToken)===String(card.dataset.playerToken));if(player?.characterId!=='jogo'||card.querySelector('.v36-jogo-quick'))return;const host=card.querySelector('.gm-resource-grid')||card.querySelector('.gm-player-head'),panel=document.createElement('div');panel.className='v36-jogo-quick';panel.innerHTML='<div><b>🔥 Jogo · Vita/Energia</b><small>Valore unico, massimo 8</small></div><div class="v36-jogo-buttons">'+[-2,-1,1,2].map(v=>'<button type="button" data-v36-jogo="'+v+'">'+(v>0?'+':'')+v+'</button>').join('')+'</div>';host?.insertAdjacentElement('afterend',panel);});}
function installGmEnhancements(){const original=getGlobal('renderGMDashboard');if(typeof original==='function'&&!original.__v36){const wrapped=function(){const out=original.apply(this,arguments);requestAnimationFrame(injectJogoQuickControls);return out;};wrapped.__v36=true;setGlobal('renderGMDashboard',wrapped);}}

function ensureStatsShell(){const screen=document.getElementById('statistics'),wrap=screen?.querySelector('.cloud-stats-wrap');if(!wrap||document.getElementById('v36StatsShell'))return;const shell=document.createElement('div');shell.id='v36StatsShell';shell.className='v36-stats-shell';shell.innerHTML='<section class="v36-stats-intro"><div><small>JJK ENERGY V36</small><h2>Statistiche semplici e utili</h2><p>Quattro sezioni: situazione attuale, partite live, storico completo e profilo Stregone.</p></div><div id="v36OnlinePill" class="v36-online-pill"><i></i><b>0 online</b></div></section><nav class="v36-stats-nav"><button class="active" data-v36-stats="overview"><span>◉</span><b>Panoramica</b><small>I numeri importanti</small></button><button data-v36-stats="live"><span>●</span><b>Partite live</b><small>Guarda senza entrare</small></button><button data-v36-stats="history"><span>▤</span><b>Storico</b><small>Account e personaggi</small></button><button data-v36-stats="profile"><span>冠</span><b>Profilo Stregone</b><small>Progressi personali</small></button></nav><div id="v36StatsOverview" class="v36-stats-panel active"></div><div id="v36StatsLive" class="v36-stats-panel"></div><div id="v36StatsHistory" class="v36-stats-panel"></div><div id="v36StatsProfile" class="v36-stats-panel"></div>';wrap.querySelector('.cloud-stats-topbar,.topbar')?.insertAdjacentElement('afterend',shell);screen.classList.add('v36-stats-active');}
function setStatsView(view){state.activeStatsView=['overview','live','history','profile'].includes(view)?view:'overview';document.querySelectorAll('[data-v36-stats]').forEach(b=>b.classList.toggle('active',b.dataset.v36Stats===state.activeStatsView));document.querySelectorAll('.v36-stats-panel').forEach(p=>p.classList.toggle('active',p.id==='v36Stats'+state.activeStatsView.charAt(0).toUpperCase()+state.activeStatsView.slice(1)));localStorage.setItem('jjk_v36_stats_view',state.activeStatsView);loadStatsView(state.activeStatsView);}
function overviewData(){return window.jjkCloudStatsState||{};}
function onlineListHtml(){if(!state.online.length)return '<div class="v36-empty">Nessun altro account online in questo momento.</div>';return '<div class="v36-online-grid">'+state.online.map(u=>'<article><span class="v36-avatar">'+esc((u.account_tag||u.display_name||'?').slice(0,1).toUpperCase())+'</span><div><b>@'+esc(u.account_tag||u.display_name||'account')+'</b><small>'+esc(u.current_screen_label||u.current_screen||'Nel sito')+(u.in_match&&u.character_id?' · '+esc(characterName(u.character_id)):'')+'</small></div><i></i></article>').join('')+'</div>';}
function renderOverview(){const root=document.getElementById('v36StatsOverview');if(!root)return;const cloud=overviewData(),totals=cloud.global?.totals||{},top=(cloud.global?.top_players||[])[0],char=(cloud.global?.characters||[]).slice().sort((a,b)=>num(b.selections)-num(a.selections))[0];root.innerHTML='<section class="v36-kpis">'+[['Partite concluse',totals.matches_played||0,'⚔'],['Giocatori registrati',totals.unique_players||0,'人'],['Partite in corso',state.live.length||totals.active_matches||0,'●'],['Online adesso',state.online.length||totals.online_players||0,'⌁']].map(([l,v,i])=>'<article><span>'+i+'</span><small>'+l+'</small><b>'+int(v)+'</b></article>').join('')+'</section><section class="v36-overview-grid"><article class="v36-feature-card"><small>Campione globale</small><h3>'+esc(top?.player_name||'In attesa')+'</h3><p>'+(top?int(top.wins)+' vittorie · '+num(top.win_rate).toFixed(1)+'% win rate':'Concludi una partita per aprire la classifica.')+'</p></article><article class="v36-feature-card"><small>Personaggio più scelto</small><h3>'+esc(char?characterName(char.character_id):'In attesa')+'</h3><p>'+(char?int(char.selections)+' selezioni · '+int(char.wins)+' vittorie':'Nessun dato disponibile.')+'</p></article></section><section class="v36-section"><header><div><small>Presenza in tempo reale</small><h3>Chi è online</h3></div><button type="button" data-v36-refresh-online>↻ Aggiorna</button></header><div id="v36OnlineList">'+onlineListHtml()+'</div></section>';}
function liveMatchHtml(match){const participants=Array.isArray(match.participants)?match.participants:[];return '<article class="v36-live-card"><header><div><span class="v36-live-badge"><i></i> LIVE</span><h3>'+esc(match.label||'Partita in corso')+'</h3><p>'+int(match.connected_players)+' connessi su '+int(match.player_count)+' giocatori · '+fmtDuration(match.duration_seconds)+'</p></div><button type="button" data-v36-watch="'+esc(match.room_id)+'">Guarda partita</button></header><div class="v36-live-roster">'+participants.map(p=>'<span><img src="'+esc(characterImage(p.character_id))+'" alt=""><b>@'+esc(p.account_tag||p.player_name||'giocatore')+'</b><small>'+esc(characterName(p.character_id))+'</small></span>').join('')+'</div><footer><span>GM '+(match.gm_online?'online':'in riconnessione')+'</span><span>'+(match.boss_rush_active?'Boss Rush attiva':'Boss Rush disattivata')+'</span></footer></article>';}
function renderLive(){const root=document.getElementById('v36StatsLive');if(!root)return;root.innerHTML='<section class="v36-section"><header><div><small>Modalità spettatore</small><h3>Partite che stanno giocando ora</h3><p>Osserva stato, personaggi e turni senza entrare nella stanza e senza poter modificare la partita.</p></div><button type="button" data-v36-refresh-live>↻ Aggiorna</button></header><div class="v36-live-list">'+(state.live.length?state.live.map(liveMatchHtml).join(''):'<div class="v36-empty">Nessuna partita è attualmente in corso.</div>')+'</div></section>';}
function historyRow(match){const players=Array.isArray(match.participants)?match.participants:[];return '<article class="v36-history-card"><header><div><small>'+fmtDate(match.ended_at)+'</small><h3>'+(match.winner_name?'Vittoria di '+esc(match.winner_name):'Partita conclusa')+'</h3><p>'+fmtDuration(match.duration_seconds)+' · '+players.length+' giocatori'+(match.boss_rush_used?' · Boss Rush':'')+'</p></div><span>'+int(match.total_techniques||0)+' tecniche</span></header><div class="v36-history-players">'+players.map(p=>'<div class="'+(p.is_winner?'winner':'')+'"><img src="'+esc(characterImage(p.character_id))+'" alt=""><span><b>@'+esc(p.account_tag||p.player_name||'account')+'</b><small>'+esc(characterName(p.character_id))+(p.is_winner?' · Vincitore':'')+'</small></span></div>').join('')+'</div></article>';}
function renderHistory(){const root=document.getElementById('v36StatsHistory');if(!root)return;root.innerHTML='<section class="v36-section"><header><div><small>Archivio partite</small><h3>Chi ha giocato e con quale personaggio</h3><p>Ogni partita mostra gli account partecipanti, il personaggio scelto e il vincitore.</p></div><button type="button" data-v36-refresh-history>↻ Aggiorna</button></header><div class="v36-history-list">'+(state.history.length?state.history.map(historyRow).join(''):'<div class="v36-empty">Lo storico si popolerà dopo le prime partite concluse.</div>')+'</div></section>';}
function achievementPreview(items){const list=(items||[]).filter(x=>x.unlocked).slice(0,8);return list.length?'<div class="v36-achievements">'+list.map(a=>'<span><i>'+esc(a.icon||'✦')+'</i><b>'+esc(a.name)+'</b></span>').join('')+'</div>':'<div class="v36-empty compact">Nessun trofeo ancora sbloccato.</div>';}
function renderProfile(){const root=document.getElementById('v36StatsProfile');if(!root)return;const account=state.profile?.account||{},personal=state.profile?.statistics||{},progress=state.progression?.progression||{},achievements=state.progression?.achievements||[],matches=num(personal.totals?.matches_played||progress.total_matches),wins=num(personal.totals?.wins||progress.wins),rate=matches?100*wins/matches:0;root.innerHTML='<section class="v36-profile-hero"><span class="v36-profile-avatar">'+esc((account.account_tag||account.display_name||'?').slice(0,1).toUpperCase())+'</span><div><small>PROFILO STREGONE</small><h2>@'+esc(account.account_tag||account.display_name||'account')+'</h2><p>'+esc(progress.title||'Stregone in crescita')+'</p><div class="v36-level-bar"><i style="--p:'+clamp(progress.progress_percent,0,100)+'%"></i></div><em>Livello '+int(progress.level||1)+' · '+int(progress.xp||0)+' XP</em></div></section><section class="v36-profile-kpis">'+[['Partite',matches],['Vittorie',wins],['Win rate',rate.toFixed(1)+'%'],['Trofei',progress.achievements_unlocked||achievements.filter(a=>a.unlocked).length]].map(([l,v])=>'<article><small>'+l+'</small><b>'+esc(v)+'</b></article>').join('')+'</section><section class="v36-section"><header><div><small>Traguardi</small><h3>Trofei sbloccati</h3></div></header>'+achievementPreview(achievements)+'</section>';}
async function loadOnline(silent=false){try{const data=await rpc('jjk_online_users_v36');state.online=Array.isArray(data)?data:[];updateOnlineUi();if(state.activeStatsView==='overview')renderOverview();}catch(error){if(!silent&&migrationError(error)){const root=document.getElementById('v36OnlineList');if(root)root.innerHTML=requirementBox();}}}
async function loadLive(silent=false){try{const data=await rpc('jjk_live_matches_v36');state.live=Array.isArray(data)?data:[];if(state.activeStatsView==='live')renderLive();if(state.activeStatsView==='overview')renderOverview();}catch(error){if(!silent){const root=document.getElementById('v36StatsLive');if(root)root.innerHTML=migrationError(error)?requirementBox():'<div class="v36-error">'+esc(error?.message||error)+'</div>';}}}
async function loadHistory(silent=false){try{const data=await rpc('jjk_match_history_v36',{p_limit:60,p_offset:0});state.history=Array.isArray(data)?data:[];if(state.activeStatsView==='history')renderHistory();}catch(error){if(!silent){const root=document.getElementById('v36StatsHistory');if(root)root.innerHTML=migrationError(error)?requirementBox():'<div class="v36-error">'+esc(error?.message||error)+'</div>';}}}
async function loadProfile(silent=false){try{const [account,statistics,progression]=await Promise.all([rpc('jjk_my_account_profile'),rpc('jjk_my_statistics'),rpc('jjk_my_progression')]);state.profile={account:account||{},statistics:statistics||{}};state.progression=progression||{};if(state.activeStatsView==='profile')renderProfile();}catch(error){if(!silent){const root=document.getElementById('v36StatsProfile');if(root)root.innerHTML='<div class="v36-error">'+esc(error?.message||error)+'</div>';}}}
async function loadStatsView(view){if(view==='overview'){renderOverview();loadOnline(true);loadLive(true);}if(view==='live'){renderLive();loadLive(false);}if(view==='history'){renderHistory();loadHistory(false);}if(view==='profile'){renderProfile();loadProfile(false);}}
function installStatsOverride(){ensureStatsShell();const original=getGlobal('openStatistics');if(typeof original==='function'&&!original.__v36){const wrapped=function(){const out=original.apply(this,arguments);setTimeout(()=>{ensureStatsShell();setStatsView(localStorage.getItem('jjk_v36_stats_view')||'overview');},80);return out;};wrapped.__v36=true;setGlobal('openStatistics',wrapped);}document.addEventListener('jjk:cloudstats',()=>{if(state.activeStatsView==='overview')renderOverview();});}

function ensureSpectatorModal(){if(document.getElementById('v36SpectatorModal'))return;const modal=document.createElement('div');modal.id='v36SpectatorModal';modal.className='v36-modal';modal.innerHTML='<section class="v36-modal-shell v36-spectator-shell"><header><div><small><i class="v36-live-dot"></i> MODALITÀ SPETTATORE</small><h2 id="v36SpectatorTitle">Partita live</h2><p id="v36SpectatorMeta">Connessione in corso…</p></div><button data-v36-close="spectator">✕</button></header><div id="v36SpectatorContent" class="v36-sheet-grid"></div><footer>Visione in sola lettura · nessun codice stanza o comando di gioco viene mostrato.</footer></section>';document.body.appendChild(modal);}
async function refreshSpectator(){if(!state.spectatorRoomId)return;const root=document.getElementById('v36SpectatorContent');try{const snap=await rpc('jjk_live_match_snapshot_v36',{p_room_id:state.spectatorRoomId}),players=Array.isArray(snap?.players)?snap.players:[];document.getElementById('v36SpectatorTitle').textContent=snap?.label||'Partita live';document.getElementById('v36SpectatorMeta').textContent=fmtDuration(snap?.duration_seconds)+' · '+players.filter(p=>!p.is_host).length+' giocatori · aggiornamento '+new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'});root.innerHTML=players.filter(p=>!p.is_host&&p.character_id).map(p=>readOnlyPlayerCard({playerToken:p.id,name:p.account_tag?'@'+p.account_tag:p.player_name,characterId:p.character_id,connected:p.is_connected,locked:p.is_locked,state:p.state||{}})).join('')||'<div class="v36-empty">Stato dei giocatori non ancora disponibile.</div>';}catch(error){if(root)root.innerHTML=migrationError(error)?requirementBox():'<div class="v36-error">'+esc(error?.message||error)+'</div>';}}
function openSpectator(roomId){ensureSpectatorModal();state.spectatorRoomId=roomId;document.getElementById('v36SpectatorModal').classList.add('show');refreshSpectator();clearInterval(state.spectatorTimer);state.spectatorTimer=setInterval(refreshSpectator,3000);}
function closeSpectator(){state.spectatorRoomId=null;clearInterval(state.spectatorTimer);state.spectatorTimer=null;document.getElementById('v36SpectatorModal')?.classList.remove('show');}
function presenceClientId(){let id=localStorage.getItem(CLIENT_ID_KEY);if(!id){id='web_'+crypto.getRandomValues(new Uint32Array(2)).join('_');localStorage.setItem(CLIENT_ID_KEY,id);}return id;}
async function heartbeat(){try{await rpc('jjk_presence_heartbeat',{p_client_id:presenceClientId(),p_screen:activeScreen()});}catch(_){}}
function updateOnlineUi(){const count=state.online.length,pill=document.getElementById('v36OnlinePill');if(pill)pill.querySelector('b').textContent=count+' online';let home=document.getElementById('v36HomeOnline');if(!home){home=document.createElement('button');home.id='v36HomeOnline';home.className='v36-home-online';home.type='button';home.innerHTML='<i></i><span><b>0 online</b><small>Presenza in tempo reale</small></span>';home.addEventListener('click',()=>{window.openStatistics?.();setTimeout(()=>setStatsView('overview'),100);});document.body.appendChild(home);}home.querySelector('b').textContent=count+' online';}
function startPresence(){heartbeat();loadOnline(true);clearInterval(state.presenceTimer);clearInterval(state.onlineTimer);state.presenceTimer=setInterval(heartbeat,20000);state.onlineTimer=setInterval(()=>loadOnline(true),15000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){heartbeat();loadOnline(true);}});window.addEventListener('focus',()=>{heartbeat();loadOnline(true);});}

function ensureAdminScreen(){if(document.getElementById('v36Admin'))return;const main=document.createElement('main');main.id='v36Admin';main.className='screen page v36-admin-screen';main.innerHTML='<section class="wrap v36-admin-wrap"><div class="topbar"><button class="back" data-v36-admin-back>←</button><h2 class="title">Amministrazione sito</h2><button class="v36-admin-refresh" data-v36-admin-refresh>↻</button></div><section class="v36-admin-hero"><div><small>AREA PROPRIETARIO</small><h3>Account, blocchi e personaggi consentiti</h3><p>Le modifiche sono convalidate da Supabase: questa schermata non appare agli utenti normali.</p></div><div><input id="v36AdminSearch" placeholder="Cerca nickname o account"><button data-v36-admin-search>Cerca</button></div></section><div id="v36AdminList" class="v36-admin-list"><div class="v36-loading">Caricamento account…</div></div></section>';document.body.appendChild(main);const action=document.querySelector('.home-actions-grid');if(action&&!document.getElementById('v36AdminHomeBtn')){const b=document.createElement('button');b.id='v36AdminHomeBtn';b.className='home-action v36-admin-home';b.innerHTML='<span class="home-action-icon">権</span><span><b>Amministrazione</b><small>Account, blocchi e personaggi</small></span>';b.addEventListener('click',openAdmin);action.appendChild(b);}const menu=document.querySelector('.v20-domain-grid');if(menu&&!menu.querySelector('[data-v36-open-admin]')){const b=document.createElement('button');b.className='v20-domain-card';b.style.setProperty('--c','#ff6b83');b.dataset.v36OpenAdmin='1';b.innerHTML='<span class="v20-domain-icon">権</span><b>Amministrazione</b><small>Gestione proprietario</small>';menu.appendChild(b);}}
function allowedCharacterEditor(account){const allowed=Array.isArray(account.allowed_character_ids)?account.allowed_character_ids:[];return '<div class="v36-character-permissions">'+Object.entries(getCharacters()).map(([id,ch])=>'<label><input type="checkbox" value="'+esc(id)+'" '+(!allowed.length||allowed.includes(id)?'checked':'')+'><img src="'+esc(ch.image)+'" alt=""><span>'+esc(ch.name.split(' ')[0])+'</span></label>').join('')+'</div>';}
function renderAdmin(){const root=document.getElementById('v36AdminList');if(!root)return;root.innerHTML=state.adminAccounts.length?state.adminAccounts.map(a=>'<article class="v36-admin-account" data-user-id="'+esc(a.user_id)+'"><header><span class="v36-avatar">'+esc((a.account_tag||a.display_name||'?').slice(0,1).toUpperCase())+'</span><div><h3>@'+esc(a.account_tag||'senza_tag')+'</h3><p>'+esc(a.display_name||'—')+' · '+int(a.matches||0)+' partite · '+int(a.wins||0)+' vittorie</p></div><i class="'+(a.online?'online':'')+'">'+(a.online?'Online':'Offline')+'</i></header><div class="v36-admin-fields"><label><span>Nome visibile</span><input data-admin-name value="'+esc(a.display_name||'')+'"></label><label><span>Stato account</span><select data-admin-blocked><option value="0" '+(!a.is_blocked?'selected':'')+'>Attivo</option><option value="1" '+(a.is_blocked?'selected':'')+'>Bloccato</option></select></label><label class="wide"><span>Motivo blocco</span><input data-admin-reason value="'+esc(a.block_reason||'')+'" placeholder="Facoltativo"></label></div><details><summary>Personaggi consentiti</summary><p>Seleziona tutti per non applicare limitazioni.</p>'+allowedCharacterEditor(a)+'</details><footer><button data-admin-save>Salva modifiche</button><button class="danger" data-admin-delete>Elimina accesso</button></footer></article>').join(''):'<div class="v36-empty">Nessun account trovato.</div>';}
async function loadAdmin(search=''){const root=document.getElementById('v36AdminList');if(root)root.innerHTML='<div class="v36-loading">Caricamento account…</div>';try{const data=await rpc('jjk_admin_dashboard_v36',{p_search:search||null,p_limit:200});state.adminAccounts=Array.isArray(data)?data:[];renderAdmin();}catch(error){if(root)root.innerHTML='<div class="v36-error">'+esc(error?.message||error)+'</div>';}}
function openAdmin(){if(!state.admin)return;try{showScreen('v36Admin');}catch(_){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id==='v36Admin'));}loadAdmin(document.getElementById('v36AdminSearch')?.value||'');}
async function checkAdmin(){try{state.admin=!!(await rpc('jjk_is_site_admin'));if(state.admin)ensureAdminScreen();}catch(_){state.admin=false;}}
async function saveAdminCard(card){const allowed=[...card.querySelectorAll('.v36-character-permissions input:checked')].map(x=>x.value),allCount=Object.keys(getCharacters()).length;try{await rpc('jjk_admin_update_account_v36',{p_user_id:card.dataset.userId,p_display_name:card.querySelector('[data-admin-name]').value.trim(),p_account_tag:null,p_is_blocked:card.querySelector('[data-admin-blocked]').value==='1',p_block_reason:card.querySelector('[data-admin-reason]').value.trim()||null,p_allowed_character_ids:allowed.length===allCount?null:allowed});notify('Account aggiornato','Le nuove regole sono già attive.','#55e39b');loadAdmin(document.getElementById('v36AdminSearch')?.value||'');}catch(error){notify('Modifica non riuscita',String(error?.message||error),'#ff637b');}}
async function deleteAdminAccount(card){const tag=card.querySelector('h3')?.textContent||'questo account';if(!confirm('Eliminare e bloccare definitivamente l’accesso di '+tag+'? Lo storico partite resterà anonimo e integro.'))return;try{await rpc('jjk_admin_delete_account_v36',{p_user_id:card.dataset.userId});notify('Accesso eliminato','L’account non può più entrare nel sito.','#ff9b55');loadAdmin(document.getElementById('v36AdminSearch')?.value||'');}catch(error){notify('Eliminazione non riuscita',String(error?.message||error),'#ff637b');}}
function boostAudio(){try{if(localStorage.getItem(AUDIO_BOOST_KEY)!=='1'){const current=num(window.JJKSfx?.getVolume?.());if(!current||current<.9)window.JJKSfx?.setVolume?.(.9);localStorage.setItem(AUDIO_BOOST_KEY,'1');}}catch(_){}const original=getGlobal('playTechniqueEffect');if(typeof original==='function'&&!original.__v36){const wrapped=function(technique){try{const name=String(technique?.name||'').toLowerCase();window.JJKSfx?.play(/meteora|fuoco|vulcan|magmatic/.test(name)?'fire':/taglio|lancia|katana|slash/.test(name)?'slash':/dominio|vuoto|santuario/.test(name)?'domain':'technique');}catch(_){}return original.apply(this,arguments);};wrapped.__v36=true;setGlobal('playTechniqueEffect',wrapped);}}
function bindEvents(){document.addEventListener('click',event=>{const close=event.target.closest('[data-v36-close]');if(close){if(close.dataset.v36Close==='spectator')closeSpectator();if(close.dataset.v36Close==='sheets')closeOtherSheets();return;}const stats=event.target.closest('[data-v36-stats]');if(stats){setStatsView(stats.dataset.v36Stats);return;}const watch=event.target.closest('[data-v36-watch]');if(watch){openSpectator(watch.dataset.v36Watch);return;}if(event.target.closest('[data-v36-refresh-online]')){loadOnline(false);return;}if(event.target.closest('[data-v36-refresh-live]')){loadLive(false);return;}if(event.target.closest('[data-v36-refresh-history]')){loadHistory(false);return;}const jogo=event.target.closest('[data-v36-jogo]');if(jogo){const card=jogo.closest('[data-player-token]');if(card)window.gmAdjustPlayer?.(card.dataset.playerToken,'energy',Number(jogo.dataset.v36Jogo));return;}if(event.target.closest('[data-v36-open-admin]')){document.getElementById('v20DomainMenu')?.classList.remove('open');openAdmin();return;}if(event.target.closest('[data-v36-admin-back]')){try{showScreen('home');}catch(_){}return;}if(event.target.closest('[data-v36-admin-refresh]')||event.target.closest('[data-v36-admin-search]')){loadAdmin(document.getElementById('v36AdminSearch')?.value||'');return;}const save=event.target.closest('[data-admin-save]');if(save){saveAdminCard(save.closest('.v36-admin-account'));return;}const del=event.target.closest('[data-admin-delete]');if(del){deleteAdminAccount(del.closest('.v36-admin-account'));return;}if(event.target.classList.contains('v36-modal')){if(event.target.id==='v36SpectatorModal')closeSpectator();if(event.target.id==='v36OtherSheetsModal')closeOtherSheets();}});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeSpectator();closeOtherSheets();}});window.addEventListener('jjk-account-ready',()=>{heartbeat();checkAdmin();loadOnline(true);});}
function wrapScreenChanges(){const original=getGlobal('showScreen');if(typeof original==='function'&&!original.__v36){const wrapped=function(id){const out=original.apply(this,arguments);setTimeout(()=>{heartbeat();updateOtherSheetsButton();if(id==='statistics'){ensureStatsShell();setStatsView(localStorage.getItem('jjk_v36_stats_view')||'overview');}},30);return out;};wrapped.__v36=true;setGlobal('showScreen',wrapped);}const renderRoom=getGlobal('renderRoomUI');if(typeof renderRoom==='function'&&!renderRoom.__v36){const wrapped=function(){const out=renderRoom.apply(this,arguments);setTimeout(updateOtherSheetsButton,0);return out;};wrapped.__v36=true;setGlobal('renderRoomUI',wrapped);}}
function init(){if(state.initialized)return;state.initialized=true;patchCharacterRules();installTojiRules();installPermanentBodyGuard();installGmEnhancements();ensureRoomSheetsUi();ensureSpectatorModal();ensureStatsShell();installStatsOverride();wrapScreenChanges();bindEvents();boostAudio();startPresence();checkAdmin();syncLocalTojiMonster(false);updateOtherSheetsButton();setInterval(()=>{updateOtherSheetsButton();injectJogoQuickControls();},1500);console.info('JJK Energy V36 ready',VERSION);}
window.JJKV36={version:VERSION,state,openSpectator,openAdmin,refreshOnline:()=>loadOnline(false),refreshHistory:()=>loadHistory(false),syncTojiMonster:syncLocalTojiMonster};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
