/* JJK Energy V39 - stable rules and smooth opponent sheets */
(function(r,f){const a=f(r||globalThis);if(typeof module==='object'&&module.exports)module.exports=a;if(r&&r.document)a.install();})(typeof window!=='undefined'?window:globalThis,function(root){
'use strict';
const VERSION='39.0.0',RANK={G4:0,G3:1,G2:2,G1:3,SS:4,SG:5},num=v=>Number.isFinite(Number(v))?Number(v):0,cap=(v,a,b)=>Math.max(a,Math.min(b,num(v)));
function resolveVariableCost(roll,energy,boss=false){const r=Math.max(0,Math.trunc(num(roll))),e=Math.max(0,num(energy)),paid=boss?0:Math.min(r,e),body=boss?r:paid;return{roll:r,paid,body,missing:Math.max(0,r-body)};}
function analyzeBlackFlashRolls(values){const rolls=(Array.isArray(values)?values:[]).map(Number);if(!rolls.length)return{ok:false,rolls:[],sum:0,error:'empty'};if(rolls.some(v=>!Number.isInteger(v)||v<1||v>6))return{ok:false,rolls,sum:0,error:'range'};for(let i=1;i<rolls.length;i++)if(rolls[i]<rolls[i-1])return{ok:false,rolls,sum:0,error:'order',index:i};return{ok:true,rolls,sum:rolls.reduce((a,b)=>a+b,0),error:null};}
function itadoriBonuses(v){const f=cap(v,0,20),o={body:0,life:0,energy:0};if(f>=4)o.body++;if(f>=8){o.body++;o.life++;}if(f>=12){o.body++;o.life++;o.energy+=2;}if(f>=16){o.body++;o.life++;o.energy+=2;}if(f>=20){o.body++;o.life++;o.energy+=2;}return o;}
function blueprints(){return{
 jogo:{maxLife:8,baseBody:5,coins:0,isJogo:true,lifeEnergyLinked:false,innateName:'Natura Vulcanica',innateEffect:'Puo muoversi liberamente fino a 4 caselle. Non puo usare il Fato.',grades:[[0,10],[7,12],[16,15],[26,18],[35,20],[45,23]].map((x,i)=>({id:['G4','G3','G2','G1','SS','SG'][i],label:['Grado 4','Grado 3','Grado 2','Grado 1','Semi Special Grade','Special Grade'][i],exp:x[0],max:x[1]})),techniques:[
 {key:'insetti',name:'Insetti Ardenti',grade:'G4',cost:5,bonus:4,image:'assets/jogo_g4.png'},
 {key:'vulcani',name:'Vulcani',grade:'G3',cost:8,bonus:6,image:'assets/jogo_sheet.png',v37JogoVolcano:true,v27CostLabel:'Costo: 8 Energia - +6 Corpo',extra:'Crea un Vulcano. PVE: nemici -2 Corpo. PVP: Jogo guadagna Energia quando altri raccolgono EM sulla casella del Vulcano.'},
 {key:'salvataggio_hanami',name:'Salvataggio di Emergenza Hanami',grade:'G2',cost:10,bonus:null,image:'assets/jogo_g2.png',v37JogoHanami:true,v27JogoHanami:true,effect:'Perdi lo scontro e tira 1d6. Con 3-6 Hanami ti salva; con 1-2 fallisce.'},
 {key:'meteora2',name:'Meteora Infuocata',grade:'G1',cost:12,bonus:9,image:'assets/jogo_g1.png',v37JogoMeteor:true,extra:'Ottieni 1 Calore, massimo 8. Questa tecnica riceve +1 Corpo per ogni Calore.'},
 {key:'bara_ferro',name:'(Dominio) Bara della Montagna di Ferro',grade:'SS',cost:18,bonus:15,image:'assets/jogo_sheet.png',v37JogoDomain:true,extra:'+1 Corpo per Vulcano, massimo +3. Distrugge una casella e crea un Cratere.'},
 {key:'placche_tettoniche',name:'Manipolazione Placche Tettoniche',grade:'SG',cost:0,bonus:null,image:'assets/jogo_sheet.png',v37JogoTectonic:true,effect:'Muovi ogni Vulcano fino a 4 caselle. Una volta per turno consumane uno per creare un Cratere.'}]},
 itadori:{name:'Yuji Itadori',baseMaxLife:4,maxLife:4,baseBody:4,coins:1,hasFingers:true,innateName:'Richiamo del Ricettacolo Perfetto',innateEffect:'1 Dito per mostro, massimo 12; Sukuna concede 5 Dita; da una casella adiacente ruba 1 Dito al possessore.',grades:[[0,10],[9,12],[19,15],[30,18],[42,20],[50,21]].map((x,i)=>({id:['G4','G3','G2','G1','SS','SG'][i],label:['Grado 4','Grado 3','Grado 2','Grado 1','Semi Special Grade','Special Grade'][i],exp:x[0],max:x[1]})),techniques:[
 {key:'pugno_divergente',name:'Pugno Divergente',grade:'G4',cost:4,bonus:4,image:'assets/itadori_g4.webp'},
 {key:'black_flash_itadori',name:'Black Flash',grade:'G3',cost:0,bonus:null,image:'assets/itadori_g1.webp',v27ItadoriBlackFlash:true,itadoriBlackFlash:true,v27CostLabel:'Costo: somma dei dadi validi',effect:'Continua finche ogni risultato e maggiore o uguale al precedente. Corpo e costo sono limitati dall Energia disponibile.'},
 {key:'manipolazione_sangue',name:'Manipolazione del Sangue',grade:'G2',cost:0,bonus:null,image:'assets/itadori_g3.webp',v37ItadoriBlood:true,v27CostLabel:'1 Vita -> 10 Energia',effect:'Una volta per turno, in qualsiasi momento, converti 1 Vita in 10 Energia.'},
 {key:'freccia_itadori',name:'Freccia Infuocata',grade:'G1',cost:10,bonus:10,lifeCost:1,image:'assets/itadori_freccia.webp'},
 {key:'richiamo_anima_sukuna',name:"(Dominio) Richiamo dell Anima di Sukuna",grade:'SS',cost:0,bonus:null,image:'assets/itadori_ss.webp',v37ItadoriSoulDomain:true,v27CostLabel:'Costo: d24 - Corpo: d24 limitato dall EM + 2d6'},
 {key:'immortalita',name:'Immortalita',grade:'SG',cost:0,bonus:null,image:'assets/itadori_taglio.webp',v37ItadoriImmortality:true,effect:'Una volta per partita, prima di morire recuperi tutta Vita ed Energia.'}]}}
}
function read(k,d=null){try{const v=(0,eval)(k);return v===undefined?d:v}catch(_){return root[k]===undefined?d:root[k]}}function write(k,v){root.__v39=v;try{(0,eval)(k+'=globalThis.__v39')}catch(_){root[k]=v}delete root.__v39}function fn(k){const v=read(k,root[k]);return typeof v==='function'?v:null}function setfn(k,v){root[k]=v;root.__v39fn=v;try{(0,eval)(k+'=globalThis.__v39fn')}catch(_){}delete root.__v39fn}function chars(){return read('characters',root.characters||{})}function cid(){return read('currentId')}function current(){return read('current')}function used(){const v=read('used',[]);return Array.isArray(v)?v:[]}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function enforce(){const a=chars(),b=blueprints();for(const id of['jogo','itadori'])if(a[id]){const image=a[id].image;Object.assign(a[id],b[id]);if(image)a[id].image=image}if(a.itadori)a.itadori.maxLife=4+itadoriBonuses(read('itadoriMaxFingers',0)).life;if(cid()==='jogo')write('current',a.jogo);if(cid()==='itadori')write('current',a.itadori)}
function finish(t,before,resolved,total,text){const list=used();if(!list.includes(t.key))list.push(t.key);write('used',list);fn('recordTechniqueUse')?.(cid(),t,resolved.paid);fn('addLog')?.('Tecnica utilizzata',t.name+': '+before+' -> '+Math.max(0,num(read('energy',0)))+' Energia. '+text);fn('saveState')?.();fn('renderAll')?.();fn('playTechniqueEffect')?.(t);fn('showModal')?.(t.name,total+' Combattimento',text)}
function execute(t,rolls){const before=Math.max(0,num(read('energy',0))),boss=!!fn('isBossRushFree')?.(),value=Array.isArray(rolls)?rolls.reduce((a,b)=>a+b,0):rolls,res=resolveVariableCost(value,before,boss);if(!boss)write('energy',before-res.paid);const base=num(fn('effectiveBaseBody')?.()??current()?.baseBody),bonus=num(read('combatBonus',0)),total=base+res.body+bonus,text=(Array.isArray(rolls)?'Dadi '+rolls.join(' + ')+' = ':'Dado d24 ')+value+'. Costo '+value+', pagato '+res.paid+'. Corpo applicato '+res.body+(res.missing?' (-'+res.missing+' per Energia insufficiente)':'')+'. Totale '+base+' + '+res.body+' + '+bonus+' = '+total+'.';finish(t,before,res,total,text)}
function patchTechniques(){const base=fn('useTechnique');if(!base||base.__v39)return;const wrap=function(k){enforce();const t=current()?.techniques?.find(x=>x.key===k);if(!t||used().includes(k))return;if(t.dynamicCost){if(fn('roomActionAllowed')&&!fn('roomActionAllowed')())return;const raw=root.prompt('Risultato d24 (1-24):'),v=Number(raw);if(raw===null)return;if(!Number.isInteger(v)||v<1||v>24)return fn('showModal')?.('Valore non valido','','Inserisci un numero da 1 a 24.');return execute(t,v)}if(cid()==='itadori'&&t.itadoriBlackFlash){if(fn('roomActionAllowed')&&!fn('roomActionAllowed')())return;const raw=root.prompt('Risultati d6 separati da virgola, ciascuno maggiore o uguale al precedente:');if(raw===null)return;const a=analyzeBlackFlashRolls(raw.split(/[^0-9]+/).filter(Boolean));if(!a.ok)return fn('showModal')?.('Black Flash non valido','',a.error==='order'?'Ogni dado deve essere maggiore o uguale al precedente.':'Usa valori da 1 a 6.');return execute(t,a.rolls)}return base.apply(this,arguments)};wrap.__v39=true;wrap.__v37=true;setfn('useTechnique',wrap)}
let open=false,timer=null,selected=null,last='';function players(){const r=read('roomSession'),me=fn('getLocalRoomPlayer')?.();return(r?.players||[]).filter(p=>!p.isHost&&p.playerToken!==me?.playerToken&&p.characterId)}function ensureViewer(){let m=document.getElementById('v39SheetsModal');if(m)return m;const s=document.createElement('style');s.textContent='#v39SheetsModal{position:fixed;inset:0;z-index:140000;display:none;padding:14px;background:#020308ed}#v39SheetsModal.show{display:grid;place-items:center}.v39box{width:min(1100px,98vw);height:min(780px,94vh);overflow:auto;padding:18px;border:1px solid #54c8ff;border-radius:22px;background:#0b111a;color:white}.v39top{display:flex;justify-content:space-between}.v39tabs,.v39stats,.v39techs{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:9px;margin:12px 0}.v39tabs button,.v39stat,.v39tech{padding:11px;border:1px solid #30455b;border-radius:13px;background:#111d2a;color:white}.v39tabs button.active{border-color:#54c8ff}.v39tech p{color:#a9bac8;font-size:.75rem}.v39close{height:42px;border-radius:12px;background:#641625;color:white}';document.head.appendChild(s);m=document.createElement('div');m.id='v39SheetsModal';m.innerHTML='<section class="v39box"><header class="v39top"><div><small>STRATEGIA IN ATTESA</small><h2>Schede degli altri giocatori</h2></div><button class="v39close">X</button></header><nav class="v39tabs"></nav><main class="v39detail"></main></section>';document.body.appendChild(m);m.querySelector('.v39close').onclick=closeViewer;m.onclick=e=>{if(e.target===m)closeViewer();const b=e.target.closest('[data-v39]');if(b){selected=b.dataset.v39;last='';refresh(true)}};return m}
function refresh(force=false){if(!open)return;const me=fn('getLocalRoomPlayer')?.();if(read('roomSession')?.phase!=='playing'||!me?.locked)return closeViewer();const ps=players(),m=ensureViewer();if(!ps.length){m.querySelector('.v39detail').innerHTML='Nessun altro giocatore.';return schedule()}if(!selected||!ps.some(p=>String(p.playerToken)===selected))selected=String(ps[0].playerToken);const p=ps.find(x=>String(x.playerToken)===selected),s=p.state||{},ch=chars()[p.characterId],sig=ps.map(x=>[x.playerToken,x.locked,x.connected,x.state?.gradeId,x.state?.life,x.state?.energy,x.state?.exp].join('|')).join(';')+'#'+selected;if(force||sig!==last){last=sig;m.querySelector('.v39tabs').innerHTML=ps.map(x=>'<button class="'+(String(x.playerToken)===selected?'active':'')+'" data-v39="'+esc(x.playerToken)+'"><b>'+esc(x.name)+'</b><br><small>'+esc(chars()[x.characterId]?.name)+' - '+esc(x.state?.gradeId||'G4')+'</small></button>').join('');const tech=(ch?.techniques||[]).filter(t=>(RANK[t.grade]??0)<=(RANK[s.gradeId||'G4']??0)),body=num(ch?.baseBody)+(p.characterId==='itadori'?itadoriBonuses(s.itadoriMaxFingers).body:0);m.querySelector('.v39detail').innerHTML='<div class="v39stats"><div class="v39stat">Vita <b>'+(s.life??'-')+' / '+(s.maxLife??ch?.maxLife??'-')+'</b></div><div class="v39stat">Energia <b>'+(s.energy??'-')+'</b></div><div class="v39stat">EXP <b>'+(s.exp??0)+'</b></div><div class="v39stat">Corpo <b>'+body+'</b></div></div><h3>Tecniche sbloccate - '+tech.length+'</h3><section class="v39techs">'+tech.map(t=>'<article class="v39tech"><b>'+esc(t.name)+' - '+esc(t.grade)+'</b><p>'+esc(t.v27CostLabel||('Costo: '+num(t.cost)+' Energia'))+'</p><p>'+esc(t.effect||t.extra||(t.bonus!=null?'+'+t.bonus+' Corpo':'Effetto speciale'))+'</p></article>').join('')+'</section>'}schedule()}
function schedule(){clearTimeout(timer);if(open)timer=setTimeout(()=>refresh(false),500)}function openViewer(){const me=fn('getLocalRoomPlayer')?.();if(!me?.locked)return fn('showModal')?.('Schede non disponibili','','Puoi consultarle soltanto quando non e il tuo turno.');document.getElementById('v37SheetsModal')?.classList.remove('show');open=true;selected=null;last='';ensureViewer().classList.add('show');refresh(true)}function closeViewer(){open=false;clearTimeout(timer);document.getElementById('v39SheetsModal')?.classList.remove('show')}
function installViewer(){const upgrade=()=>{const b=document.getElementById('v36OtherSheetsBtn');if(b)b.id='v39OtherSheetsBtn'};upgrade();document.addEventListener('click',e=>{if(e.target.closest?.('#v39OtherSheetsBtn')){e.preventDefault();e.stopImmediatePropagation();openViewer()}},true);new MutationObserver(upgrade).observe(document.body,{childList:true,subtree:true})}
function audit(){const b=blueprints(),a=chars(),c={version:VERSION,variableCost:resolveVariableCost(16,14).body===14,blackFlash:analyzeBlackFlashRolls([1,2,2,6]).sum===11,jogo:a.jogo?.grades?.map(x=>x.max).join()==b.jogo.grades.map(x=>x.max).join(),itadori:a.itadori?.grades?.map(x=>x.max).join()==b.itadori.grades.map(x=>x.max).join(),patched:!!fn('useTechnique')?.__v39};c.ok=Object.entries(c).filter(([k])=>!['version','ok'].includes(k)).every(([,v])=>v===true);root.JJKV39Audit=c;console.info('JJK V39 audit',c);return c}
function install(){if(root.__JJK_V39__)return;root.__JJK_V39__=true;const start=()=>{enforce();patchTechniques();installViewer();setTimeout(()=>{enforce();patchTechniques();audit();fn('renderAll')?.()},250)};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start()}
return{version:VERSION,resolveVariableCost,analyzeBlackFlashRolls,itadoriBonuses,blueprints,install};
});
